services:
  db:
    image: webapp-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3406:3306
    networks:
      - gsystem-network
    volumes:
      - db_data:/var/lib/mysql

  WebApp:
    image: webapp_project
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
      MYSQLCONNECTION__MYSQLCONNECTIONSTRING: "Server=db;DataBase=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD};SslMode=none;"
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - db
    networks:
      - gsystem-network

networks:
  gsystem-network:
    driver: bridge

volumes:
  db_data: